### ISSUE TITLE
Syntax highlighting not working.

### ISSUE THREAD

**Issue by toots** [mcfiredrill/vim-liquidsoap#1]
Hi,

I've followed the instructions but the plugin doesn't seem to pick up syntax highlighting..

Relevant portions of `~/.vimrc`:

```
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

 " let Vundle manage Vundle
 " required!
Bundle 'gmarik/vundle'
Bundle 'mcfiredrill/vim-liquidsoap'
    au BufRead,BufNewFile *.liq set filetype=liquidsoap

set nocompatible      " We're running Vim, not Vi!
syntax on             " Enable syntax highlighting
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins
```

I've followed install instructions with `vundle` and pluging is listed as loaded when running `:scriptnames`. I've also tried to `:set filetype=liquidsoap` with no success.

Any suggestion? :-)

**Comment by mcfiredrill** [comment]
Thanks for trying it out!

I believe I had the directory structure set up wrong, the latest commit should have fixed it!

**Comment by toots** [comment]
Indeed, thanks!
